import { Inter, Raleway } from 'next/font/google';
import './globals.css';
import styles from './layout.module.css';
import Link from 'next/link';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });
const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Head>
        <link
          rel='preconnect'
          href='https://fonts.googleapis.com'
        ></link>
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossorigin
        ></link>
        <link
          href='https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap'
          rel='stylesheet'
        ></link>
      </Head>
      <body className={`${inter.className}`}>
        <header className={styles.header}></header>
        {children}
      </body>
    </html>
  );
}
